---
# This playbook deploys the whole application stack in this site.
# This playbook is intended for application deployment without any s3a support
# If you want to use s3a, please use another playbook: site-s3a.yml
- name: apply common configuration to all nodes
  hosts: all:!localhost
  remote_user: '{{ remote_user }}'
  become: yes
  become_method: sudo
  vars_files:
    - "vars/{{ deploy_method }}.yml"
    - "vars/resources.yml"
  roles:
    - { role: ansiblebit.oracle-java,
      oracle_java_set_as_default: yes,
      oracle_java_version: 8,
      oracle_java_version_update: 131,
      oracle_java_version_build: 11,
      oracle_java_rpm_url: "http://download.oracle.com/otn-pub/java/jdk/{{ oracle_java_version }}u{{ oracle_java_version_update }}-b{{ oracle_java_version_build }}/d54c1d3a095b4ff2b6607d096fa80163/{{ oracle_java_rpm_filename }}",
      when : install_java == "yes"}
    - {role: common, when : install_common == "yes"}
    - {role: hadoop-common-without-s3a, when : install_hadoop_common == "yes"}
    - {role: hive-without-s3a, when : install_hive == "yes"}
    - {role: spark, when: install_spark == "yes"}
    - {role : maven, when : install_maven == "yes"}
    - {role: hive-testbench, when : install_hive_testbench == "yes"}
    - {role: presto-without-s3a, when : install_presto == "yes"}
#     - {role: test, when: test_t == "yes"}
